### ISSUE TITLE
Data mgmt app: have a default projection

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-applications#96] opened 2015-04-14 21:08 UTC
Would be nice to pre-populate projection with

```json
  "projection": {
    "field": "*",
    "include": true,
    "recursive": true
  },
```

**Comment by jewzaam** [comment] 2015-04-14 21:08
updated to be recursive true, oops

**Comment by alechenninger** [comment] 2015-04-14 23:05
Duplicate of #67

**Closed** 2015-04-16 14:50 UTC
Labels: duplicate, enhancement
